travis:
  secure:
    BINSTAR_TOKEN: xAVnKqlAwgBEz9PwXZlURL2QuYKSnqWllT/Le7vPJYcTxmfO9ewzJooDeGISL7n/eEmlGydUqD0eA4kaZRy+fo/BNfBEOtfaG6470SrNQESWjZuox38bUeTgDtVQViNj9S0H84aRjgXuSez22WpuvDVRH5vzOyMZ13g/t01CRbERQmR5CI6dqteKZOX/ITQ77gt7xfWj1kUoV7X7xRX4Y6UpCCMjDWMl/JsB1N4buxEBm7VFN90zLWknzUrDegmlwqhhoKJvrJOjwrpilAE2b1CKwlrrSyYSIA2KOTYlVCjMXyiBJCilnGNEsQWLvCqDZ3jXm5PT66OJfUzztKSEBqENwoYEvftZ1SZseEDVtVDEY5PpGsygrEgNWF2BJILzzHVqvmF7+kHoBkdBZgBYjB8hvUlG+mpdibuw01KDf8TZ5FclyMBdTZ3xj8gmUdQK60CPsVig748PIx8VTFIKYf1rakjhNnzaPeZt9JGxqDcDDUuBK8s7AWSGWroy3qgdYbiLGrlHfGfiinWwQSr1uneWJNqLT8Db/GHKfQum075uNBFqD9NKuBKAJUR+vVXYH1hVGsbUgHcrWG6tBdc7qOT8+W0Nv/wpF/RbhTX3TDv62uqv6gbrZr+pDnUBpcOSWZM6E/sO0NJ3hCwO9XQY7rOGAmISHSFyGJ0/N2HEiwc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
